'use client'
import { FormEvent, useState } from 'react'
import { products } from '@/lib/products'
import { useCart } from '@/components/cart'

export default function SubscriptionsPage(){
 const {add}=useCart(); const [plan,setPlan]=useState('monthly'); const [roast,setRoast]=useState(products[0].id); const [submitted,setSubmitted]=useState(false)
 const selected=products.find(p=>p.id===roast) ?? products[0]
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault(); add({...selected,id:`${selected.id}-${plan}`,name:`${selected.name} — ${plan==='monthly'?'Monthly':'Bi-weekly'}`});setSubmitted(true)}
 return <main className="mx-auto max-w-3xl px-5 py-14 md:py-20"><p className="text-xs uppercase tracking-[.22em] text-primary">A standing invitation</p><h1 className="mt-4 max-w-2xl text-5xl leading-tight md:text-6xl">Keep good coffee close.</h1><p className="mt-5 max-w-xl leading-7 text-muted-foreground">Choose a roast and a rhythm, then we&apos;ll add it to your cart. Your first payment follows the same checkout flow; renewals are handled manually for now.</p><form onSubmit={submit} className="mt-10 flex flex-col gap-7"><fieldset className="flex flex-col gap-3"><legend className="mb-1 text-sm font-semibold">Choose your rhythm</legend>{[['monthly','Monthly'],['bi-weekly','Bi-weekly']].map(([value,label])=><label key={value} className="flex items-center gap-3 border border-border p-4"><input type="radio" name="plan" value={value} checked={plan===value} onChange={()=>setPlan(value)}/><span>{label}</span><span className="ml-auto text-xs text-muted-foreground">KSh {selected.priceKsh.toLocaleString()} / delivery</span></label>)}</fieldset><fieldset className="flex flex-col gap-3"><legend className="mb-1 text-sm font-semibold">Choose your roast</legend>{products.map(p=><label key={p.id} className="flex items-center gap-3 border border-border p-4"><input type="radio" name="roast" value={p.id} checked={roast===p.id} onChange={()=>setRoast(p.id)}/><span>{p.name}</span><span className="ml-auto text-xs text-muted-foreground">{p.roast}</span></label>)}</fieldset><div className="grid gap-5 md:grid-cols-3"><label className="flex flex-col gap-2 text-sm md:col-span-1">Name<input required name="name" className="border border-border bg-background p-3"/></label><label className="flex flex-col gap-2 text-sm">Phone<input required type="tel" name="phone" className="border border-border bg-background p-3"/></label><label className="flex flex-col gap-2 text-sm">Email<input required type="email" name="email" className="border border-border bg-background p-3"/></label></div><button type="submit" className="self-start bg-primary px-6 py-4 text-sm font-semibold text-primary-foreground transition-colors hover:bg-foreground">Add subscription to cart</button>{submitted&&<p role="status" className="text-sm text-primary">Subscription added. Continue to your cart when you&apos;re ready.</p>}</form></main>
}
